-- 创建数据库
CREATE DATABASE education DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

-- 1.编码类别表
CREATE TABLE department (
  id INT(10) NOT NULL AUTO_INCREMENT,
  typeNo VARCHAR(16) NOT NULL UNIQUE,
  NAME VARCHAR(20) NOT NULL,
  description VARCHAR(200)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 2.编码信息表
CREATE TABLE CODE(
  id INT(10) NOT NULL AUTO_INCREMENT,
  codeNo VARCHAR(16) NOT NULL UNIQUE,
  NAME VARCHAR(20) NOT NULL,
  description VARCHAR(200)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 3.专业-系别关系表
CREATE TABLE dept_major(
  id INT(10) NOT NULL AUTO_INCREMENT,
  roleNo VARCHAR(16) NOT NULL UNIQUE,
  NAME VARCHAR(20) NOT NULL,
  description VARCHAR(200)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 4.角色-权限表
CREATE TABLE role_power(
  id INT(10) NOT NULL AUTO_INCREMENT,
  departmentNo VARCHAR(16) NOT NULL UNIQUE,
  NAME VARCHAR(20) NOT NULL,
  description VARCHAR(200)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 5.课程信息表
CREATE TABLE course(
  id INT(10) NOT NULL AUTO_INCREMENT,
  courseNo VARCHAR(16) NOT NULL UNIQUE,
  NAME VARCHAR(20) NOT NULL UNIQUE
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 6.班级信息表
CREATE TABLE class(
  id INT(10) NOT NULL AUTO_INCREMENT,
  classNo VARCHAR(16) NOT NULL UNIQUE,
  NAME VARCHAR(20) NOT NULL UNIQUE,
  major VARCHAR(16) NOT NULL
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 7.用户信息表
CREATE TABLE USER(
  id INT(10) NOT NULL AUTO_INCREMENT,
  account VARCHAR(16) NOT NULL,
  PASSWORD VARCHAR(16) NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  sex VARCHAR(6) NOT NULL,
  age INT(6) NOT NULL,
  role VARCHAR(16) NOT NULL,
  pid VARCHAR(20) NOT NULL UNIQUE 
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 8.教师信息表
CREATE TABLE teacher(
  id INT(10) NOT NULL AUTO_INCREMENT,
  teacherNo VARCHAR(16) NOT NULL UNIQUE,
  USER VARCHAR(16) NOT NULL,
  role VARCHAR(16) NOT NULL,
  major VARCHAR(16) NOT NULL,
  state VARCHAR(16) NOT NULL 
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 9.教师-课程关系表
CREATE TABLE teacher_course(
  id INT(10) NOT NULL AUTO_INCREMENT,
  teacher varchar(10) NOT NULL,
  course varchar(10) NOT NULL
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 10.学生信息表
CREATE TABLE student(
  id INT(10) NOT NULL AUTO_INCREMENT,
  stuNo VARCHAR(20) NOT NULL UNIQUE,
  USER VARCHAR(16) NOT NULL,
  major VARCHAR(16) NOT NULL,
  joinTime DATE NOT NULL,
  overTime DATE,
  state VARCHAR(16) NOT NULL
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
